// JavaScript Document
/*jshint esversion: 6 */

const questionBank = {
//		0= question, 1= correct answer, 2-4=distactors, 5= puzzle, 6= category
		0 : ["In the Star Trek series, the part of Ensign Chekov was played by who?",
				 "Walter Koenig",
				 "Brent Spiner",
				 "Leonard Nimoy",
				 "Kirk",
				 "Star Trek",
				 "Show Biz"],
		1 : ["What actor played the part of Data in Star Trek, the Next Generation?",
				 "Brent Spiner",
				 "Walter Koenig",
				 "Leonard Nimoy",
				 "Kirk",
				 "Artificial Humanoid Life",
				 "Thing"],
		2 : ["In 1995, 13 books were sold every minute in U.S. on what subject?",
				 "Star Trek",
				 "The Twilight Zone",
				 "Spot",
				 "Twilight",
				 "Chart Topper",
				 "Event"],
		3 : ["Apart from Star Trek, the actors Kirk, Scott, Spock, and Sulu appeared on what other program?",
				 "The Twilight Zone",
				 "Star Wars",
				 "FTU",
				 "The Outer Limits",
				 "Working Together Again",
				 "Phrase"],
		4 : ["What was used as Dr McCoy's medical scanner in Star Trek?",
				 "A Salt Shaker",
				 "Spot",
				 "Spiner",
				 "Twilight",
				 "On Stage and Back Stage Working Together Again Stage",
				 "Phrase"],
		5 : ["What was the first science fiction show to air regularly on U.S. television?",
				 "Captain Video and His Video Rangers",
				 "Lost in Space",
				 "Flash Gordon",
				 "Batman",
				 "dumont network",
				 "Thing"],
		6 : ["Who was the captain of the USS Enterprise in the pilot episode of 'Star Trek'?",
				 "Captain Christopher Pike",
				 "Captain Philip Fancis Queeg",
				 "Captain James T. Kirk",
				 "Captain Benjamin Lafayette Sisko",
				 "to go where no man has gone before",
				 "Phrase"],
		7 : ["What is notable about the starship Moya in 'Farscape'?",
				 "It's a living, sentient biomechanical being.",
				 "It's powered by a Terminex bomb, which could wipe out an entire solar system if detonated.",
				 "It's actually a rogue planet moving through the galaxy.",
				 "It can time travel.",
				 "interfacing and communicating starship",
				 "Phrase"],
		8 : ["Why is Fox Mulder of 'The X-Files' obsessed with extraterrestrials and alien abductins?",
				 "He witnessed his sister being abducted by aliens when he was a child.",
				 "He had visions that he was destined to communicate with an alien species.",
				 "His father was killed by an extraterrestrial death squad in the Korean War.",
				 "Cancer Man tricked him.",
				 "samantha",
				 "Person"],
		9: ["In what 1983 miniseries did 50 massive alien motherships appear above the major cities of Earth?",
				 "V",
				 "Otherworld",
				 "Alien Nation",
				 "Q",
				 "short lived weekly series",
				 "Phrase"],
		10: ["How are the characters Sarah Manning, Katja Obinger, Alison Hendrix and Cosima Niehaus connected on 'Orphan Black'?",
				 "They're identical clones of each other.",
				 "Their blood serum can cure cancer.",
				 "They're members of a government espionage team.",
				 "Mind Meld",
				 "there are more than four clones",
				 "Phrase"],
		11: ["Complete this line from 'The Greatest American Hero' theme song: 'Believe it or not, I'm...",
				 "Walking on air.",
				 "The greatest of all.",
				 "A man who can fly.",
				 "your hero baby.",
				 "alien super suit",
				 "Phrase"],
		12: ["In 'Earth 2,' what had the government group The Council been using planet G889 for many years before the colonists arrived?",
				 "They used it as an off-world penal colony, sending criminals there to serve life sentences.",
				 "They used it to breed an army of genetically modified clone super soldiers.",
				 "They used it to dump toxic waste.",
				 "Observation Post",
				 "left many questions unanswered",
				 "Phrase"],
		13: ["In 'Quantum Leap,' what is the name of the artificial intelligence that helps Sam and Al?",
				 "Ziggy",
				 "Roddy",
				 "Aladdin",
				 "Computer",
				 "make the correct changes and fix history",
				 "Phrase"],
		14: ["What is the name of the ship on 'Firefly?'",
				 "Serenity",
				 "Firefly",
				 "River Tam",
				 "Enterprise",
				 "firefly class vessel",
				 "Phrase"],
		15: ["Where was the USS Voyager stranded in 'Star Trek: Voyager?'",
				 "the Delta Quadrant",
				 "the Neutral Zone",
				 "Bernoulli Space",
				 "the Bad Lands",
				 "strange energy wave shunts",
				 "Phrase"],
		16: ["What dimension is, 'a dimension not only of sight and sound, but of mind?'",
				 "the Twilight Zone",
				 "the Outer Limits",
				 "the Island",
				 "Membata",
				 "five years",
				 "Phrase"],
		17: ["What 1987 sci-fi series featured light effects that interacted with toys produced to accompany the show?",
				 "Captain Power and the Soldiers of the Future",
				 "Wing Commander",
				 "Silverhawks",
				 "Babylon 5",
				 "j michael straczynski",
				 "Person"],
		18: ["'Captica' is a prequel for what 2004 series, which was itself a reboot of a 1980 series?",
				 "Battlestar Galactica",
				 "Sliders",
				 "seaQuest DSV",
				 "Star Trek",
				 "destruction of twelve colonies",
				 "Phrase"],
		19: ["What was the original function of the spaceship Red Dwarf?",
				 "mining",
				 "warship",
				 "colonization",
				 "exploration",
				 "Jupiter Mining Corporation",
				 "Phrase"],
		20: ["What show is about the adventures of a Time Lord?",
				 "Dr. Who",
				 "Lexx",
				 "Quantum Leap",
				 "Time Lord",
				 "Time Lord from the planet Gallifrey",
				 "Phrase"],
		21: ["What did the survivors have to do every 108 minutes to prevent a catastrophe on 'Lost?'",
				 "Enter the numbers 4, 8, 15, 16, 23 and 42 into a computer and press 'Execute'",
				 "Scream, 'WALT!'",
				 "Broadcast a radio signal from the Pearl.",
				 "Run",
				 "Inside the Swan",
				 "Phrase"],
		22: ["Which series featured a man named Number Six trapped in The Village?",
				 "The Prisoner",
				 "The HighwayMan",
				 "Thunderbirds",
				 "The Spectator",
				 "unidentified British intelligence agent",
				 "Phrase"],
		23: ["What decade is the lead character seemingly transported to in both versions of 'Life on Mars?'",
				 "the 1970s",
				 "2030",
				 "the beginning of the 35th century",
				 "2520",
				 "third planet from the sun",
				 "Phrase"],
		24: ["What phrase did Gene Roddenberry use to describe the show when he originally pitched the first 'Star Trek' series to network executives?",
				 "Wagon Train' to the stars",
				 "A TV show where no man has gone before.",
				 "'Black Sheep Squadron' in space",
				 "Up, Up and Away",
				 "military supply wagon train",
				 "Phrase"],
		25: ["Where is the Control Voice about to take you when you hear the lines, 'There is nothing wrong with your television set. You are about to participate in a great adventure. You are about to experience the awe and mystery which reaches from the inner mind to...'",
				 "the Outer Limits",
				 "Mindwarp Alpha",
				 "the Dark Side",
				 "the Twilight Zone",
				 "anthology series",
				 "Phrase"],
		26: ["Which TV series based on a film franchise starred an actor from 'Firefly' and an actor who would go on to star in 'Game of Thrones?'",
				 "Terminator: The Sarah Connor Chronicles",
				 "Stargate",
				 "Alien Nation",
				 "The Incredible Hulk",
				 "summer glau",
				 "Actor"],
		27: ["'The Incredible Hulk' starred Bill Bixby as Bruce Banner, who transformed into the Hulk when angry. Who portrayed the Hulk?",
				 "Lou Ferrigno",
				 "Charles Atlas",
				 "Frank Stallone",
				 "Mark Ruffalo",
				 "Hearing impaired ferrigno",
				 "Phrase"],
		28: ["Why did 'The Six Million Dollar Man' cost $6 million?",
				 "Three of his limbs and one eye had been replaced by cybernetic implants.",
				 "That was what the U.S. government paid to ransom him from communist agents.",
				 "That was the R&D cost of the synthetic serum that granted him superhuman abilities.",
				 "Inflation",
				 "we have the technology",
				 "Phrase"],
		29: ["What was the setting of the British 70s series 'Space: 1999?'",
				 "Moonbase Alpha",
				 "London",
				 "Orbital Station Epsilon",
				 "Deep Space 9",
				 "Hurled out of orbit",
				 "Phrase"],
		30: ["What is the purpose of the space station Babylon 5?",
				 "It's a center for galactic diplomacy and trade.",
				 "It's a mining complex extracting resources from asteroids.",
				 "It's an outpost guarding against imminent invasion by the Vorlons.",
				 "Observation",
				 "center for diplomacy among multiple alien races",
				 "Phrase"],
		31: ["How many people (including, occasionally, computers) were in Roj Blake's group in his battle against the Terran Federation?",
				 "7",
				 "5",
				 "13",
				 "20",
				 "british science fiction television series",
				 "Phrase"],
		32: ["What cyberpunk character took his name from a sign he saw moments before he died and was recreated as a digital entity?",
				 "Max Headroom",
				 "Bio Hazard",
				 "High Voltage",
				 "computer generated character",
				 "Matt Frewer",
				 "Actor"],
		33: ["What is the addictive soft drink in 'Futurama?'",
				 "Slurm",
				 "Freem",
				 "Nuka-Cola",
				 "Dr. Breen's Private Reserve",
				 "Slurm factory on the planet wurmulon",
				 "Place"],
		34: ["What was the name of the robot from 'Lost in Space' famous for saying, 'Danger, Will Robinson!'",
				 "the Robot",
				 "Robby",
				 "VINCENT",
				 "High Voltage",
				 "Forbidden Planet",
				 "Place"],
};
